# Generated by Django 5.0.6 on 2024-06-23 17:38

import datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(help_text='Select tags for this question', related_name='questions', to='qa.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(help_text='Enter tags for a question (e.g. Linux, DB, Network etc.)', max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('tag_text'), name='tag_text_case_insensitive_unique', violation_error_message='Tag already exists (case insensitive match)'),
        ),
    ]
