# Generated by Django 5.0.6 on 2024-07-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_remove_answer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes_count',
        ),
    ]
