# Generated by Django 5.0.6 on 2024-07-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_text']},
        ),
    ]
